source 'https://rubygems.org'


git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

# Windows Directory Monitor (WDM) is a library which can be used to monitor directories for changes
gem 'wdm', '>= 0.1.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.1'

# Pg is the Ruby interface to the PostgreSQL RDBMS.
gem 'pg'
# This is a JSON implementation as a Ruby extension in C.
gem 'json'

# ActiveRecord connection adapter for PostGIS, based on postgresql and rgeo
gem 'activerecord-postgis-adapter'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
end
